name: Build & Deploy

on:
  schedule:
    - cron: "5 20 * * *"
  workflow_dispatch:
  push:

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [20.x]
        sqlite: [3.40.0]

    steps:
    - uses: actions/checkout@v2
    - run: bash data-prepare-sh/create_db.sh
    - name: Update resources
      uses: JamesIves/github-pages-deploy-action@v4.6.4
      with:
        branch: gh-pages # The branch the action should deploy to.
        folder: public # The folder the action should deploy.
        clean: false
        single-commit: true


